name: Drupal CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  drupal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install DDEV
        run: |
          curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh
          bash install_ddev.sh

      - name: Start DDEV and install Drupal
        run: |
          ddev config --project-type=drupal11 --docroot=web --create-docroot
          ddev start
          ddev composer create "drupal/recommended-project:^11" --no-interaction
          ddev config --project-type=drupal11 --docroot=web --create-docroot --no-interaction
          ddev start
          ddev composer install
          ddev drush site:install standard --account-name=admin --account-pass=admin --site-name="Drupal Assessment" --yes
          ddev drush en custom_module --yes
          ddev drush cr

      - name: Run PHP CodeSniffer (phpcs)
        run: ddev phpcs --standard=Drupal,DrupalPractice web/modules/custom
